### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by abhimanyuahuja** [jim3/Network-Packet-Analyzer#6]
is this really working after locally setting up , i tried setting up and got no output

**Comment by jim3** [comment]
> is this really working after locally setting up , i tried setting up and got no output

Hi! :) I am not surprised and my apologies. I am still in the learning phases of using `git` and it's been a bit of mess learning about branches...etc.. so the version(s) you got could have been broken.

I have just pushed a new version that should work. The bad news is that the new version _does_ introduce new dependencies :/ as I've added the feature of being able to write the results to a MongoDB Atlas database using Mongoose. A `npm install` should take care of that but you'll need to still get a MongoDB Atlas account in order to get a "Connection String" to place inside your `.env` file (along with your iplocation API key). That could be a bit of a pain if you've never done that. Here are the steps to get that done: https://www.mongodb.com/docs/guides/atlas/connection-string/


But! What I *recommend* is to just comment out the MongoDB code in the `indexRoute.js` file, that is much easier. 

### How to run the app w/o MongoDB

You should be able to comment out the MongoDB code and run the app w/o MongoDB. Here are the steps:

In the `indexRoute.js` file:

1. comment out:

```js
const Packet = require("../models/Packet");`
```

2. The MongoDB connection code:

```js
const mongoose = require("mongoose");
const uri = process.env.MONGO_DB_CONNECTION_STRING;

mongoose
    .connect(uri, {
        dbName: "packet_analyzer", // name of the database
        useNewUrlParser: true,
        useUnifiedTopology: true,
    })
    .then(() => console.log("Successfully connected to MongoDB."))
    .catch((err) => console.error("Connection error", err));
```

3. The call to `Packet.create()`:

```js
const createPacket = async (analysisResult) => {
    // Creates a new packet in the database (collection: packets)
    const { ipAddresses, ipDetails, macAddresses, udpPorts, tcpPorts } = analysisResult;
    Packet.create({ ipAddresses, ipDetails, macAddresses, udpPorts, tcpPorts }).then((packet) => {
        console.log("Packet created: ", packet);
        return packet;
    });
};
```

4. and lastly, comment out the call to `createPacket()` in your indexRoute.js file

```js
const savedPacket = await createPacket(analysisResult);
```

There is a `Packet.js` in the models folder that you can also comment out. After that you should be able to run the app w/o MongoDB..if I missed something let me know.

Also, make sure you got your `.env` file setup with your iplocation API key as well. You can't get the ip details w/o that.

I'll try and update the README.md file to reflect these changes as soon as I get a chance. Thanks for trying it out! :)
